### PR TITLE
Release

### PR DESCRIPTION
**Pull request by davazp**

### CODE REVIEW

**Comment by davazp** [comment]
@timoweave could you have a look and try the `next` branch? if it works for you I'll merge it into msater.

**Comment by timoweave** [comment]
oh, busy with company-graphql.el work... I can resume this part of it again...

let's add some testcase buttercup/ert. Could we  pick one of the TDD?

https://www.gnu.org/software/emacs/manual/html_node/ert/index.html
https://github.com/jorgenschaefer/emacs-buttercup

**Comment by davazp** [comment]
Sure. I would just use `ert`, being built-in makes it convenient.  I'll set it up.

**Comment by timoweave** [comment]
ok `ert` it is. should we put all the test file in subdirectory `tests/`?

**Comment by timoweave** [comment]
Hey David,
I was distracted by company coding.... here [company-graphql](https://github.com/timoweave/company-graphql), 
which need to work on fragments/union type.... but will do it later...
and will get this `graphql-mode` release done first.

**Pull request merged**
